### ISSUE TITLE
Improve settings management

### ISSUE THREAD

**Issue by evertiro** [RyanEHenderson/Pelagius#4]
Currently, the bot token is setup using an environment variable, the log channel and prefix are hard-coded, and everything else is only configurable in-channel. This should be simplified such that it's all handlable through a single configuration file. @RyanEHenderson assuming that I'm not going to get throat-punched for asking this... do you have a preferred config file format? JSON? YAML? ..._shudders_... INI?

**Comment by AnOliveBranch** [comment]
I typically use YAML for configs, probably stemming from how I started programming with Java for Minecraft and they usually use a YAMLConfiguration

**Comment by evertiro** [comment]
That doesn't sound terribly convincing... is that "I want to use YAML" or "I usually use YAML but..."

**Comment by AnOliveBranch** [comment]
I'm most used to YAML but I'm open to other options, just not as familiar with them for configs. Should probably just go YAML
